# Generated by Django 5.0.3 on 2024-04-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_description_alter_game_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_played', models.DateField(verbose_name='Played Game Last On Date')),
                ('reason_thrown_away', models.CharField(choices=[('O', 'Game was to old'), ('H', 'Game was to hard'), ('E', 'Game was to easy')], default='O', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
